### ISSUE TITLE
我在运行代码时遇到错误

### ISSUE THREAD

**Issue by TewodrosBewuket** [neardws/Game-Theoretic-Deep-Reinforcement-Learning#30]
亲爱的作者们，您好：

我正在读你的论文，给我留下了深刻的印象。但是当我尝试运行代码时出现此错误。
请帮助我解决这个错误
 @neardws 

(environment) teddy@teddy-HP-Notebook:~/Desktop/Game-Theoretic-Deep-Reinforcement-Learning-main/Experiment$ python run_d4pg.py 
2023-10-12 02:51:53.432688: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-10-12 02:51:53.432719: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/teddy/Desktop/Game-Theoretic-Deep-Reinforcement-Learning-main/Experiment/run_d4pg.py", line 5, in <module>
    from Agents.D4PG_new.agent import D4PG
  File "/home/teddy/Desktop/Game-Theoretic-Deep-Reinforcement-Learning-main/Agents/D4PG_new/agent.py", line 24, in <module>
    from acme import datasets
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/acme/datasets/__init__.py", line 18, in <module>
    from acme.datasets.reverb import make_reverb_dataset
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/acme/datasets/reverb.py", line 22, in <module>
    from acme.adders import reverb as adders
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/acme/adders/reverb/__init__.py", line 20, in <module>
    from acme.adders.reverb.base import DEFAULT_PRIORITY_TABLE
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/acme/adders/reverb/base.py", line 28, in <module>
    import reverb
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/reverb/__init__.py", line 27, in <module>
    from reverb import item_selectors as selectors
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/reverb/item_selectors.py", line 19, in <module>
    from reverb import pybind
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/reverb/pybind.py", line 6, in <module>
    _load_op_library.reraise_wrapped_error(e)
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/reverb/platform/default/load_op_library.py", line 47, in reraise_wrapped_error
    raise error
  File "/home/teddy/anaconda3/envs/environment/lib/python3.9/site-packages/reverb/pybind.py", line 4, in <module>
    from .libpybind import *
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
(environment) teddy@teddy-HP-Notebook:~/Desktop/Game-Theoretic-Deep-Reinforcement-Learning-main/Experiment$

**Comment by Weiji-0823** [comment]
请问下你的问题是都解决 了吗

**Comment by TewodrosBewuket** [comment]
是的，解决了

**Comment by Sophie2222** [comment]
你好，我也遇到了和你一样的问题，方便的话，可以告诉我你的解决方法吗

**Comment by SuperLuckyStar666** [comment]
楼主您好，请问这篇论文的Table 1中 𝑙𝑒（ Location of edge node 𝑒）的值是如何设置的呢？用的是数据集中的数据吗？我在代码中没找到边缘节点位置值设置的这个代码。

**Comment by wkyd** [comment]
请问，您有没有遇到如下问题，恳求获得您的指点，谢谢！
<img width="1080" alt="9b39218a5d24eeda05738d44a9a9a3b" src="https://github.com/user-attachments/assets/0e7ace9e-b428-4587-9bd6-c1b9cf9da0ee" />
<img width="1145" alt="04c7b3b738c07d5cf148b0c502fa262" src="https://github.com/user-attachments/assets/19edfb84-2cd3-442c-b76a-4d2f83379eaf" />
